# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
# Copyright (C) 2014 Continuent, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.  You may obtain
# a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.

# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'getMySQLPackageName') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    packageType   = args[0]
    build         = args[1]
    version       = args[2]
    os            = lookupvar('operatingsystem')
    osversion     = lookupvar('operatingsystemmajrelease')
    osreleasename = lookupvar('lsbdistcodename')
    packageServer = nil
    packageClient = nil


    if (os !~ /(?i:centos|redhat|oel|OracleLinux|amazon|ubuntu|debian)/)
      raise Puppet::ParseError, "Unsupported Operating System - #{os} "
    end

    if build == 'percona'
      if (os =~ /(?i:centos|redhat|oel|OracleLinux|amazon)/)
        if (version !~ /(?i:5.1|5.5|5.6)/)
          raise Puppet::ParseError, "Unsupported Version (#{version})  for the Percona Repo on #{os}"
        end
        version=version.gsub(".", "")
        packageServer="Percona-Server-server-#{version}"
        packageClient="Percona-Server-client-#{version}"
      else
        if (version !~ /(?i:5.6)/)
          raise Puppet::ParseError, "Unsupported Version (#{version}) for the Percona Repo on #{os}"
        end
        packageServer="percona-server-server-#{version}"
        packageClient="percona-server-client-#{version}"
      end
    end

    if build == 'mariadb'
      if (version !~ /(?i:5.5|10.0)/)
        raise Puppet::ParseError, "Unsupported Version (#{version}) for the Mariadb Repo on #{os}"
      end

      if (os =~ /(?i:centos|redhat|oel|OracleLinux|amazon)/)
        packageServer="MariaDB-server"
        packageClient="MariaDB-client"
      else
        packageServer="mariadb-server"
        packageClient="mariadb-client"
      end
    end

    #5.7. is not supported my the puppetlab module as it regnerates old variables
    if build == 'mysql'
      if (version !~ /(?i:5.5|5.6)/)
        raise Puppet::ParseError, "Unsupported Version (#{version}) for the MySQL Repo on #{os}"
      end

      if (os =~ /(?i:centos|redhat|oel|OracleLinux|amazon)/) and  osversion == '5'
        raise Puppet::ParseError, "MySQL repo is Unsupported on Centos5"
      end

      if (os =~ /(?i:ubuntu|debian)/) and  (version !~ /(?i:5.6)/)
        raise Puppet::ParseError, "Unsupported Version (#{version}) for the MySQL Repo on #{os}"
      end
      if (os =~ /(?i:debian)/)
        raise Puppet::ParseError, "MySQL repo is Unsupported on Debian"
      end
      if (os =~ /(?i:ubuntu)/)  and  (osreleasename =~ /(?i:lucid)/)
        raise Puppet::ParseError, "MySQL repo is Unsupported  on Lucid"
      end
      if (os =~ /(?i:amazon)/)
		case version
		when '5.7'
			packageServer="mysql57-server"
			packageClient="mysql57"
		when '5.6'
			packageServer="mysql56-server"
			packageClient="mysql56"
		when '5.5'
			packageServer="mysql55-server"
			packageClient="mysql55"
		else
			packageServer="mysql-server"
			packageClient="mysql"
		end

      else
		packageServer="mysql-community-server"
		packageClient="mysql-community-client"
      end
    end

    if packageType=='server'
      return packageServer
    else
      return packageClient
    end

  
  end
end
